# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "obs", "firefox" ]
  pull_request:
    branches: [ "obs", "firefox" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        bash install_prereq_ubuntu.sh
    - name: Package an app
      run: |
        sudo mkdir /out/
        bash download.sh
        python build_a_pkg.py
    - name: Test with pytest
      uses: actions/upload-artifact@v4.4.3
      with:
          # Artifact name
          name: artifact.pkg
          # A file, directory or wildcard pattern that describes what to upload
          path: /out/*.pkg
